version: '3.9'
services:
  delta:
    build: .
    container_name: delta
    restart: always
    ports:
      - "1313:1313"
      - "1414:1414"
      - "3005:3005"
      - "3000:3000"
      - "1314:1314"
